version: '2'
services:
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/var/lib/redis/data'
  db:
    image: postgres:9.6
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  web:
    image: paullj1/hackthearch:latest
    env_file: .env
    command: bundle exec puma -C "config/puma.rb" -b "ssl://0.0.0.0:3000?key=certs/server.key&cert=certs/server.crt"
    volumes:
      - .:/hta
    ports:
      - "443:3000"
    depends_on:
      - db
      - redis
    external_links:
      - db:db
      - redis:redis

volumes:
  redis:
  postgres:
